"""Update SLA and Notification models

Revision ID: 2b49a7188278
Revises: 79e41e076d02
Create Date: 2026-09-02 15:56:51.747850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b49a7188278'
down_revision = '79e41e076d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_submitted', sa.Boolean(), nullable=True),
    sa.Column('issue_assigned', sa.Boolean(), nullable=True),
    sa.Column('assignment_updated', sa.Boolean(), nullable=True),
    sa.Column('status_changed', sa.Boolean(), nullable=True),
    sa.Column('comment_added', sa.Boolean(), nullable=True),
    sa.Column('sla_warning', sa.Boolean(), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=True),
    sa.Column('issue_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('escalation_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('issue_slas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warning_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('breach_notification_sent', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sla_policies', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('issue_slas', schema=None) as batch_op:
        batch_op.drop_column('breach_notification_sent')
        batch_op.drop_column('warning_sent')

    with op.batch_alter_table('escalation_records', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
