"""real issue models

Revision ID: 79e41e076d02
Revises: c278829ad6b2
Create Date: 2026-08-31 18:37:07.003551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e41e076d02'
down_revision = 'c278829ad6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('issue_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED', name='issuestatus'), nullable=True),
    sa.Column('new_status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED', name='issuestatus'), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_number', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('citizen_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'), nullable=False))
        batch_op.add_column(sa.Column('official_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED', name='issuestatus'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_issue_department_id'))
        batch_op.create_index(batch_op.f('ix_issues_issue_number'), ['issue_number'], unique=True)
        pass
        batch_op.create_foreign_key('fk_issues_created_by_users', 'users', ['created_by'], ['id'])
        batch_op.drop_column('reported_by')
        batch_op.drop_column('department_id')
        batch_op.drop_column('priority')

    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.VARCHAR(length=8), nullable=False))
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('reported_by', sa.INTEGER(), nullable=False))
        pass
        batch_op.create_foreign_key('fk_issues_department_id_departments', 'departments', ['department_id'], ['id'])
        batch_op.create_foreign_key('fk_issues_reported_by_users', 'users', ['reported_by'], ['id'])
        batch_op.drop_index(batch_op.f('ix_issues_issue_number'))
        batch_op.create_index(batch_op.f('idx_issue_department_id'), ['department_id'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED', name='issuestatus'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
        batch_op.drop_column('closed_at')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('official_priority')
        batch_op.drop_column('citizen_priority')
        batch_op.drop_column('address')
        batch_op.drop_column('created_by')
        batch_op.drop_column('issue_number')

    with op.batch_alter_table('issue_categories', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('icon')
        batch_op.drop_column('description')

    op.drop_table('issue_status_history')
    op.drop_table('issue_attachments')
    # ### end Alembic commands ###
