"""Initialize real User model

Revision ID: c278829ad6b2
Revises: 
Create Date: 2026-08-31 17:05:47.340093

"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c278829ad6b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('issue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=True),
    sa.Column('total_word_count', sa.Integer(), nullable=True),
    sa.Column('words_per_minute', sa.Float(), nullable=True),
    sa.Column('topic_count', sa.Integer(), nullable=True),
    sa.Column('topic_switch_count', sa.Integer(), nullable=True),
    sa.Column('decision_count', sa.Integer(), nullable=True),
    sa.Column('action_item_count', sa.Integer(), nullable=True),
    sa.Column('unresolved_question_count', sa.Integer(), nullable=True),
    sa.Column('risk_count', sa.Integer(), nullable=True),
    sa.Column('average_transcript_confidence', sa.Float(), nullable=True),
    sa.Column('owner_assignment_rate', sa.Float(), nullable=True),
    sa.Column('deadline_assignment_rate', sa.Float(), nullable=True),
    sa.Column('action_completion_rate', sa.Float(), nullable=True),
    sa.Column('meeting_effectiveness_score', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('analytics_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    with op.batch_alter_table('meeting_analytics', schema=None) as batch_op:
        batch_op.create_index('idx_meeting_analytics_meeting_id', ['meeting_id'], unique=False)

    op.create_table('transcript_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('speaker', sa.String(length=255), nullable=True),
    sa.Column('topic_metadata', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=True),
    sa.Column('end_time', sa.Float(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.String(length=1000), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcript_embeddings', schema=None) as batch_op:
        batch_op.create_index('idx_transcript_embeddings_meeting', ['meeting_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'MUNICIPAL_OFFICER', 'FIELD_WORKER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('boundary_geojson', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('subscribed_events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('task_text', sa.Text(), nullable=False),
    sa.Column('normalized_task_text', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('deadline_text', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('NEEDS_REVIEW', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'CANCELLED', name='actionitemstatus'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source_start_seconds', sa.Float(), nullable=True),
    sa.Column('source_end_seconds', sa.Float(), nullable=True),
    sa.Column('source_segment_id', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index('idx_action_items_meeting_id', ['meeting_id'], unique=False)
        batch_op.create_index('idx_action_items_owner', ['owner_user_id'], unique=False)
        batch_op.create_index('idx_action_items_status', ['status'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_prefix')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index('idx_api_keys_prefix', ['key_prefix'], unique=False)

    op.create_table('employee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', name='issuestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('suggested_category', sa.String(length=100), nullable=True),
    sa.Column('category_confidence', sa.Float(), nullable=True),
    sa.Column('suggested_priority', sa.String(length=50), nullable=True),
    sa.Column('priority_reason', sa.Text(), nullable=True),
    sa.Column('priority_confidence', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('is_prediction_accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index('idx_issue_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_issue_department_id', ['department_id'], unique=False)
        batch_op.create_index('idx_issue_status', ['status'], unique=False)
        batch_op.create_index('idx_issue_ward_id', ['ward_id'], unique=False)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('calendar_provider', sa.String(length=50), nullable=True),
    sa.Column('summary_approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_summary_shared', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index('idx_meetings_calendar_event_id', ['calendar_event_id'], unique=False)

    op.create_table('sla_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='issuepriority'), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=False),
    sa.Column('escalation_time_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('previous_assignee', sa.Integer(), nullable=True),
    sa.Column('new_assignee', sa.Integer(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['new_assignee'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_assignee'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_type', sa.Enum('MEETING_SUMMARY', 'ACTION_ITEM', 'DECISION', 'RISK', 'TRANSCRIPT_SEGMENT', name='targetentitytype'), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('edited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('previous_content', sa.JSON(), nullable=False),
    sa.Column('new_content', sa.JSON(), nullable=False),
    sa.Column('edit_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.create_index('idx_version_entity', ['target_entity_type', 'target_entity_id'], unique=False)

    op.create_table('escalation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_from', sa.Integer(), nullable=True),
    sa.Column('escalated_to', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['escalated_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['escalated_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('assignment_status', sa.Enum('ASSIGNED', 'ACCEPTED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='assignmentstatus'), nullable=False),
    sa.Column('assignment_note', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_issue_assignment_status', ['issue_id', 'assignment_status'], unique=False)

    op.create_table('issue_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_slas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('sla_policy_id', sa.Integer(), nullable=False),
    sa.Column('response_due_at', sa.DateTime(), nullable=False),
    sa.Column('resolution_due_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('response_breached', sa.Boolean(), nullable=True),
    sa.Column('resolution_breached', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['sla_policy_id'], ['sla_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_approval_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('target_entity_type', sa.Enum('MEETING_SUMMARY', 'ACTION_ITEM', 'DECISION', 'RISK', 'TRANSCRIPT_SEGMENT', name='targetentitytype'), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ORGANIZER', 'HOST', 'PARTICIPANT', 'REVIEWER', 'VIEWER', name='participantrole'), nullable=False),
    sa.Column('participation_status', sa.Enum('INVITED', 'ACCEPTED', 'DECLINED', 'TENTATIVE', name='participationstatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index('idx_participant_meeting', ['meeting_id'], unique=False)
        batch_op.create_index('idx_participant_user', ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.Enum('ISSUE_SUBMITTED', 'ISSUE_MOVED_REVIEW', 'ISSUE_ASSIGNED', 'ASSIGNMENT_ACCEPTED', 'ASSIGNMENT_REJECTED', 'ISSUE_IN_PROGRESS', 'ISSUE_RESOLVED', 'ISSUE_CLOSED', 'ISSUE_REOPENED', 'NEW_COMMENT', 'APPROVAL_REQUIRED', 'SLA_APPROACHING', 'SLA_BREACHED', 'ISSUE_ESCALATED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_user_is_read', ['user_id', 'is_read'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_user_is_read')

    op.drop_table('notifications')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index('idx_participant_user')
        batch_op.drop_index('idx_participant_meeting')

    op.drop_table('meeting_participants')
    op.drop_table('meeting_comments')
    op.drop_table('meeting_approval_records')
    op.drop_table('issue_slas')
    op.drop_table('issue_comments')
    with op.batch_alter_table('issue_assignments', schema=None) as batch_op:
        batch_op.drop_index('idx_issue_assignment_status')

    op.drop_table('issue_assignments')
    op.drop_table('escalation_records')
    with op.batch_alter_table('content_versions', schema=None) as batch_op:
        batch_op.drop_index('idx_version_entity')

    op.drop_table('content_versions')
    op.drop_table('assignment_history')
    op.drop_table('sla_policies')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('idx_meetings_calendar_event_id')

    op.drop_table('meetings')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index('idx_issue_ward_id')
        batch_op.drop_index('idx_issue_status')
        batch_op.drop_index('idx_issue_department_id')
        batch_op.drop_index('idx_issue_created_at')

    op.drop_table('issues')
    op.drop_table('employee_profiles')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('idx_api_keys_prefix')

    op.drop_table('api_keys')
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index('idx_action_items_status')
        batch_op.drop_index('idx_action_items_owner')
        batch_op.drop_index('idx_action_items_meeting_id')

    op.drop_table('action_items')
    op.drop_table('webhook_endpoints')
    op.drop_table('wards')
    op.drop_table('users')
    with op.batch_alter_table('transcript_embeddings', schema=None) as batch_op:
        batch_op.drop_index('idx_transcript_embeddings_meeting')

    op.drop_table('transcript_embeddings')
    with op.batch_alter_table('meeting_analytics', schema=None) as batch_op:
        batch_op.drop_index('idx_meeting_analytics_meeting_id')

    op.drop_table('meeting_analytics')
    op.drop_table('issue_categories')
    op.drop_table('departments')
    # ### end Alembic commands ###
